### ISSUE TITLE
Find worm gears and screws

### ISSUE THREAD

**Issue by XDleader555** [OpenCT/model#3]

**Comment by XDleader555** [comment]
Meccano Spares Gears, 40:1 reduction

**Comment by TheThirdOne** [comment]
link

**Comment by XDleader555** [comment]
Worm: http://www.meccanospares.com/32-BR-N.html
Grub: http://www.meccanospares.com/69a-BK-N.html
Gear: http://www.meccanospares.com/31-BR-O.html
