### ISSUE TITLE
Create x-ray source mount

### ISSUE THREAD

**Issue by XDleader555** [OpenCT/model#9]

**Comment by TheThirdOne** [comment]
This should be a box surrounding the x-ray source with a hole for x-rays to come out and to mount to. This box will be made of lead and filled with oil for heat dissipation.

**Comment by TheThirdOne** [comment]
Was not solved. It **needs** the lead shielding and oil.

**Comment by TheThirdOne** [comment]
There is a package that may help. This is on hold.

**Comment by XDleader555** [comment]
X-ray source mounted with lead box surrounding
